#!/bin/bash
# Diagnostic script to check why SSH is hanging

echo "=== SSH Hang Diagnostic Commands ==="
echo ""
echo "Run these commands on the server to diagnose the hang:"
echo ""
echo "1. Check if SSH is waiting for something:"
echo "   sudo systemctl status sshd"
echo ""
echo "2. Check SSH config for problematic settings:"
echo "   sudo grep -E '(Banner|PrintMotd|UsePAM|GSSAPI)' /etc/ssh/sshd_config"
echo ""
echo "3. Check recent SSH connection attempts:"
echo "   sudo tail -20 /var/log/auth.log | grep sshd"
echo ""
echo "4. Check if there are any hanging SSH processes:"
echo "   ps aux | grep sshd"
echo ""
echo "5. Test SSH config for errors:"
echo "   sudo sshd -t"
echo ""
echo "6. Check if PAM is causing issues:"
echo "   sudo grep -i pam /etc/ssh/sshd_config"
echo ""
echo "7. Try connecting locally to see if it hangs:"
echo "   ssh -v localhost 'echo test'"
echo ""

